Web_Comic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from comic import views
from profiles import views as profiles_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.Home_view, name='home'),
    path('OverView/<int:comic_id>/', views.Detail_comic, name='OverView'),
    path('view/<int:tableChap_id>/', views.view_comic, name='view'),
    path('phieuluu/', views.PhieuLuuView, name='phieuluu'),
    path('phieuluufull/', views.PhieuLuuFullView, name='phieuluufull'),


    path('18+/', views.up18_view, name='18+'),
    path('18-/', views.Under18_view, name='18-'),

    path('accounts/', include('django.contrib.auth.urls')),

    path('login/', profiles_views.loginView.as_view(), name='login'),
    path('register/', profiles_views.RegisterView.as_view(), name='register'),
    path('register/ok/', profiles_views.SiteRegisterOk.as_view(), name='register_ok'),
    path('logout/', profiles_views.SiteLogOut.as_view(), name='logout'),

    path('profile/', profiles_views.ProfileEditView.as_view(), name='profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comic/models.py
from datetime import datetime

from django.db import models


class Comic(models.Model):
    name = models.CharField(max_length=1000)
    types = models.CharField(max_length=100)
    excerpt = models.TextField(max_length=200)
    description = models.TextField()
    picture = models.ImageField(upload_to='comic_picture')

    def __str__(self):
        return self.name


class DetailComic(models.Model):
    comic = models.ForeignKey(Comic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    types = models.CharField(max_length=50)
    description = models.TextField()
    avatar = models.ImageField(upload_to='avatar_comic')

    def __str__(self):
        return self.name


class TableChap(models.Model):
    chapComic = models.ForeignKey(Comic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    stt = models.PositiveSmallIntegerField(default=0)
    chapSo = models.PositiveSmallIntegerField(default=0)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name


class ViewComic(models.Model):
    viewChap = models.ForeignKey(TableChap, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    anhChap = models.ImageField(upload_to='chap_image')

    def __str__(self):
        return self.name

profiles/models.py
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=50,
        unique=True,
        help_text=_('Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = None
    last_name = None
    full_name = models.CharField(_('full_name'), max_length=255, blank=True)
    email = models.EmailField(_('email address'), unique=True)

    avatar = models.URLField(blank=True, max_length=1000)

    address = models.CharField(_('address'), max_length=500, blank=True)
    year_birth = models.PositiveSmallIntegerField(null=True, blank=True)
    about = models.TextField(blank=True)

    def __str__(self):
        return self.username

profiles/forms.py
from captcha.fields import ReCaptchaField
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField

User = get_user_model()


class RegisterForm(UserCreationForm):
    capcha = ReCaptchaField()

    class Meta:
        model = User
        fields = ('username', 'email')
        field_classes = {'username': UsernameField}
        widgets = {
            'email': forms.EmailInput(attrs={'required': True})
        }


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('full_name', 'address', 'year_birth', 'about')

profiles/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, FormView, UpdateView


from profiles.forms import RegisterForm

User = get_user_model()


class loginView(LoginView):
    template_name = 'login.html'


class RegisterView(FormView):
    template_name = 'register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        data = form.cleaned_data
        new_user = User.objects.create_user(
            username=data['username'],
            password=data['password1'],
            email=data['email']
        )
        url = f"{reverse('register_ok')}?username={new_user.username}"
        from pprint import pprint;
        pprint(url)
        return redirect(url);


class SiteRegisterOk(TemplateView):
    template_name = "register_ok.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.GET.get('username')
        return context


class SiteLogOut(LogoutView):
    template_name = 'logout.html'


class ProfileEditView(LoginRequiredMixin, UpdateView):
    template_name = 'profile.html'
    model = User
    fields = ['full_name', 'address', 'year_birth', 'about']
    success_url = reverse_lazy('profile')

    def get_object(self, queryset=None):
        return self.request.user

templates/18+.html
{% extends 'base.html' %}
{% block title %}Trên 18 Tuổi (18+)-MSIComic{% endblock %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    {% for items in list_comic_18cong %}
                        <div class="card_item">
                            <div class="card-body-item">
                                <a href="{% url 'OverView' items.id %}"><img src="{{ items.picture.url }}" width="170" height="235" style="border-radius: 10px;" alt=""></a>
                                <div class="content-card">
                                    <a href=""><h3>{{ items.name }}</h3></a>
                                    <a href=""><h6>{{ items.types }}</h6></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-md-4">
                    {% for items in list_comic_18cong2 %}
                        <div class="card_item">
                            <div class="card-body-item">
                                <a href="{% url 'OverView' items.id %}"><img src="{{ items.picture.url }}" width="170" height="235" style="border-radius: 10px;" alt=""></a>
                                <div class="content-card">
                                    <a href=""><h3>{{ items.name }}</h3></a>
                                    <a href=""><h6>{{ items.types }}</h6></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-md-4">
                    {% for items in list_comic_18cong3 %}
                        <div class="card_item">
                            <div class="card-body-item">
                                <a href="{% url 'OverView' items.id %}"><img src="{{ items.picture.url }}" width="170" height="235" style="border-radius: 10px;" alt=""></a>
                                <div class="content-card">
                                    <a href=""><h3>{{ items.name }}</h3></a>
                                    <a href=""><h6>{{ items.types }}</h6></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/18-.html
{% extends 'base.html' %}
{% block title %}Trên 18 Tuổi (18+)-MSIComic{% endblock %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    {% for items in list_comic_18tru %}
                        <div class="card_item">
                            <div class="card-body-item">
                                <a href="{% url 'OverView' items.id %}"><img src="{{ items.picture.url }}" width="170" height="235" style="border-radius: 10px;" alt=""></a>
                                <div class="content-card">
                                    <a href="{% url 'OverView' items.id %}"><h3>{{ items.name }}</h3></a>
                                    <a href=""><h6>{{ items.types }}</h6></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-md-4">
                    {% for items in list_comic_18tru2 %}
                        <div class="card_item">
                            <div class="card-body-item">
                                <a href="{% url 'OverView' items.id %}"><img src="{{ items.picture.url }}" width="170" height="235" style="border-radius: 10px;" alt=""></a>
                                <div class="content-card">
                                    <a href="{% url 'OverView' items.id %}"><h3>{{ items.name }}</h3></a>
                                    <a href=""><h6>{{ items.types }}</h6></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-md-4">
                    {% for items in list_comic_18tru3 %}
                        <div class="card_item">
                            <div class="card-body-item">
                                <a href="{% url 'OverView' items.id %}"><img src="{{ items.picture.url }}" width="170" height="235" style="border-radius: 10px;" alt=""></a>
                                <div class="content-card">
                                    <a href="{% url 'OverView' items.id %}"><h3>{{ items.name }}</h3></a>
                                    <a href=""><h6>{{ items.types }}</h6></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/OverView.html
{% extends 'base.html' %}

{% block title %} Gioi thieu {% endblock %}

{% block content %}
    <div class="container">
        <div class="card" style="padding: 10px;">
            <div class="card-body" style="padding: 10px">
                {% if detail %}
                    {% for items in detail.detailcomic_set.all %}
                        <div class="media" style="float: left;padding-right: 20px;"><img src="{{ items.avatar.url }}"
                                                                                         width="250" height="300">
                        </div>
                        <div class="media-body">
                            <h3>{{ items.name }}</h3>
                            <h5>Tác Giả: {{ items.author }}</h5>
                            <h5>Thể Loại: <a href="{% if items.types == 'Phiêu Lưu' %}{% url 'phieuluu' %}{% endif %}">{{ items.types }}</a></h5>
                            <h5>Tình Trạng: Đang cập nhật</h5>
                            <div class="myBox">
                                <h6>{{ items.description }}</h6>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <table align="center">
                    <tr>
                        <td colspan="4"><h4>Chapter</h4></td>
                    </tr>
                    <tr>
                        <th>Thu Tu</th>
                        <th>Tap</th>
                        <th>Ngay Phat Hanh</th>
                        <th>Luot Xem</th>
                    </tr>

                    {% if detail %}
                        {% for items in detail.tablechap_set.all %}
                            <tr>
                                <td>{{ items.stt }}</td>
                                <td><a href="{% url 'view' items.id %}">Chapter {{ items.chapSo }}</a></td>
                                <td>{{ items.date }}</td>
                                <td>100</td>
                                '
                            </tr>
                        {% endfor %}
                    {% endif %}

                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}Đăng Nhập - MSIComic{% endblock %}

{% block content %}
<div class="container">
    <div class="card" style="padding: 10px; margin-top: 10px;">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Đăng Nhập</button>
                <p>
                    Nếu bạn chưa có tài khoản hãy
                <a href="{% url 'register' %}"> Đăng Ký</a>
                </p>
            </form>
        </div>
    </div>

</div>
{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4 text-center">
        <p>Ban da thoat tai khoang</p>

        <a href="/">Quay tra lai trang chu</a>
    </div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block title %}Điêu Chỉnh Thông tin{% endblock %}

{% block content %}
    <p style="padding-left: 1500px;"><a href="{% url 'logout' %}" class="btn btn-danger"><i class="fa fa-sign-out"></i> Log-Out</a></p>
    <div class="container">
        <p style="padding-left: 990px; margin-top: -35px;">xin chao <strong>{{ user.username }}</strong></p>

        <div class="card">
            <div class="card-body">
                <h2>Thông Tin Cá Nhân</h2>
                <form method="post" class="profile">{% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary">Update</button>

                    <a href="{% url 'home' %}" style="text-decoration: none; padding: 10px;">Quay lai trang chu</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %}Đăng Ký - MSIComic{% endblock %}

{% block content %}
<div class="container">
    <div class="card" style="padding: 10px; margin-top: 10px;">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Đăng Ký</button>
            </form>
        </div>
    </div>

</div>
{% endblock %}

templates/register_ok.html
{% extends 'base.html' %}
{% block title %}Đăng Ký - MSIComic{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <p>Chúc mừng bạn đã đăng ký thành công tài khoản <strong>{{ username }}</strong></p>
            <p>Cảm ơn bạn đã đăng ký thành viên tại <strong>MSICmoic</strong></p>

            <a href="/" class="btn btn-primary">Tro ve trang chu</a>
        </div>
    </div>
</div>
{% endblock %}

templates/view.html
{% extends 'base.html' %}
{% block title %}MSIComic{% endblock %}

{% block content %}
    {% if ViewComic %}
        {% for items in ViewComic.viewcomic_set.all %}
            <div class="container" style="margin-top: 50px;">
                <p style="text-align: center;"><img src="{{ items.anhChap.url }}" style="width: 700px;"></p>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}